- neuer Standard-/Beispiel-Endpoint
- runtime_structure
- scripts/ Ordner
- scripts/system
- scripts/checks
- scripts/maintenance
- scripts/docs
- maintenance/
- reports/
- docs/
- reboot.sh Varianten
- jrbot_boot_report.sh Erkennung
- audit_jr-bot-network-health.sh Erkennung
- tree_snapshot
- profile_detected: legacy / template / hybrid / unknown
- deviations
